### ISSUE TITLE
Fehler nach Installation Contao 4.4.20

### ISSUE THREAD

**Issue by cstrobe** [intelligentspark/contao4-randomarticle#4]
Hallo,

wir wollten die frühere randomarticle Erweiterung (terminal42) für unsere Contao 4.4.20 Installation nutzen und haben daher über packagist die intelligentspark/contao4-randomarticle installiert.

Installation und Aufruf im Backend waren problemlos.
Bei der Einrichtung gab es jedoch Schwierigkeiten. Nach der Einbindung des Moduls konnten die entsprechenden Artikel nicht mehr bearbeitet werden.
Beim Speichern/Schließen kam schließlich eine Fehlermeldung, die uns zur Deinstallation der Erweiterung zwang.

Code:
Attempted to load class "BackendTemplate" from namespace "IntelligentSpark\RandomArticle". Did you forget a "use" statement for another namespace?

Leider reichen unsere Kenntnisse nicht aus, um den Fehler zu beheben, aber vielleicht fühlt sich jemand berufen die Erweiterung lauffähig zu machen.

**Comment by fiedsch** [comment]
In https://github.com/intelligentspark/contao4-randomarticle/blob/master/src/Resources/contao/modules/ModuleRandomArticle.php#L46 has to be

```php
$objTemplate = new \Contao\BackendTemplate('be_wildcard');
```

or you have to use

```php
use Contao\BackendTemplate;
```

**Comment by fredbliss** [comment]
Thank you!  It is now fixed.
