### ISSUE TITLE
Module class does not exist

### ISSUE THREAD

**Issue by netzarbeiter** [intelligentspark/contao4-randomarticle#5]
Contao 4.4.26 / contao4-randomarticle 2.1

Trying to display the module in the frontend end up with the following error message:

`Module class "IntelligentSpark\RandomArticle\ModuleRandomArticle" (module "randomarticle") does not exist`

**Comment by xchs** [comment]
I have got the same problem.

@intelligentspark Does this extension work with the current version of Contao 4.4.35?

I have tried to display some random articles on the website but apparently it doesn't work. The error message specified above by @netzarbeiter is logged in the system log.

I used the following default settings in the front end module and integrated the module via the page layout:

![randomarticle](https://user-images.githubusercontent.com/1218766/53846131-1e7dda80-3fac-11e9-834f-d0150190edb0.png)

**Comment by fritzmg** [comment]
Do namespaced classes work with classmap autoloading? I am not sure.

All the classes should be moved away from the `src/Resources/contao` directory and instead be placed in the appropriate namespace in `src/`.

e.g. `src/Resources/contao/modules/ModuleRandomArticle.php` should be moved to `src/FrontendModule/ModuleRandomArticle.php` and its namespace should be changed to `IntelligentSpark\RandomArticle\FrontendModule` etc.

// ah, I see the problem now: https://github.com/intelligentspark/contao4-randomarticle/pull/8

**Comment by xchs** [comment]
After applying the fix https://github.com/intelligentspark/contao4-randomarticle/pull/8 I still get the same error logged in the system log:

```
Module class "IntelligentSpark\RandomArticle\ModuleRandomArticle" (module "randomarticle") does not exist
```

No random article is displayed either.

What else I did:
* rebuilt the cache via Contao Manager
* deleted manually the folder `var/cache`
* created a new front end module "Random article"

@netzarbeiter Does the fix from https://github.com/intelligentspark/contao4-randomarticle/pull/8 work for you?

**Comment by fritzmg** [comment]
@xchs it works for me. Have you required `dev-master`?

**Comment by xchs** [comment]
Sorry, my bad. I missed that. Thank you, @fritzmg
