### ISSUE TITLE
Load-options seems not to be working

### ISSUE THREAD

**Issue by ghost** [intelligentspark/contao4-randomarticle#7]
The options for loading new articles seems not to be working. No matter what options I choose (each page load, number of page loads or whole session) - a new article is loaded on every page load.

![module-configuration](https://user-images.githubusercontent.com/29429097/54362287-f3a91b80-4668-11e9-8829-8c290be81d71.jpg)

Any ideas what's going wrong? 

We have included the module on the right column in our layout and configured to show only the articles teaser with a link to a new page with the entire article content.

**Comment by fredbliss** [comment]
Hi @FRappsil  - I don't truly actively maintain this package at the moment, but I'll see if I can figure out why that might be.  I'm happy to take in PRs for it, though!

**Comment by fredbliss** [comment]
@fritzmg - would this be something you'd have the ability to take a look at?

**Comment by fritzmg** [comment]
Done: https://github.com/intelligentspark/contao4-randomarticle/pull/11 ;)

**Comment by fredbliss** [comment]
Nice!  Thanks @fritzmg!

**Comment by fritzmg** [comment]
No problem. Btw. why are you deleting the old release tags? You shouldn't do that.

**Comment by ghost** [comment]
Hey guys,

thanks for working on this. Have now installed Version 2.2 (18.3.2019, 05:23:48) and had partly success. 

I'm showing the articles teaser on a (static) right column of my layout. This teaser is still refreshed on every single page load. No matter which configuration option I use. My goal is to show a new teaser only once a session.

**Comment by fritzmg** [comment]
Can anyone else confirm this?
